# Generated by Django 3.2.16 on 2022-11-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['created'], 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterModelOptions(
            name='wish',
            options={'ordering': ['order', 'created'], 'verbose_name_plural': 'Wishes'},
        ),
        migrations.AddField(
            model_name='wish',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
