# Generated by Django 3.2.16 on 2022-11-03 17:47

from django.db import migrations, models
import django_wishlist.storage_backend


class Migration(migrations.Migration):

    dependencies = [
        ('django_wishlist', '0002_auto_20221101_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(null=True, storage=django_wishlist.storage_backend.PublicMediaStorage, upload_to=''),
        ),
        migrations.AddField(
            model_name='wish',
            name='image',
            field=models.ImageField(null=True, storage=django_wishlist.storage_backend.PublicMediaStorage, upload_to=''),
        ),
    ]
