# Generated by Django 3.2.16 on 2022-11-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_wishlist', '0003_auto_20221103_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='gifted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='django_wishlist.wish')),
            ],
            options={
                'verbose_name_plural': 'Gifts',
                'ordering': ['created'],
            },
        ),
    ]
