# Generated by Django 3.2.16 on 2022-11-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_wishlist', '0004_auto_20221104_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='email_template_material',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='email_template_money_limited',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='email_template_money_unlimited',
            field=models.TextField(blank=True),
        ),
    ]
