# Generated by Django 3.2.16 on 2022-11-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_wishlist', '0005_auto_20221107_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
